In [1]:
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d.axes3d as axes3d

In [17]:
#df = pd.read_fwf('GSE6186_series_matrix.txt')
df = pd.read_csv('oil temperature 1.csv', parse_dates=["date"])

In [18]:
df.head(10)

,TimeID,date,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
0,0,2016-07-01 00:00:00,5.827,2.009,1.599,0.462,4.203,1.340,30.531000
1,1,2016-07-01 01:00:00,5.693,2.076,1.492,0.426,4.142,1.371,27.787001
2,2,2016-07-01 02:00:00,5.157,1.741,1.279,0.355,3.777,1.218,27.787001
3,3,2016-07-01 03:00:00,5.090,1.942,1.279,0.391,3.807,1.279,25.044001
4,4,2016-07-01 04:00:00,5.358,1.942,1.492,0.462,3.868,1.279,21.948000
5,5,2016-07-01 05:00:00,5.626,2.143,1.528,0.533,4.051,1.371,21.174000
6,6,2016-07-01 06:00:00,7.167,2.947,2.132,0.782,5.026,1.858,22.792000
7,7,2016-07-01 07:00:00,7.435,3.282,2.310,1.031,5.087,2.224,23.143999
8,8,2016-07-01 08:00:00,5.559,3.014,2.452,1.173,2.955,1.432,21.667000
9,9,2016-07-01 09:00:00,4.555,2.545,1.919,0.817,2.680,1.371,17.445999

In [19]:
df.info

<bound method DataFrame.info of        TimeID                date    HUFL   HULL   MUFL   MULL   LUFL   LULL  \
0           0 2016-07-01 00:00:00   5.827  2.009  1.599  0.462  4.203  1.340
1           1 2016-07-01 01:00:00   5.693  2.076  1.492  0.426  4.142  1.371
2           2 2016-07-01 02:00:00   5.157  1.741  1.279  0.355  3.777  1.218
3           3 2016-07-01 03:00:00   5.090  1.942  1.279  0.391  3.807  1.279
4           4 2016-07-01 04:00:00   5.358  1.942  1.492  0.462  3.868  1.279
...       ...                 ...     ...    ...    ...    ...    ...    ...
17415   17415 2018-06-26 15:00:00  -1.674  3.550 -5.615  2.132  3.472  1.523
17416   17416 2018-06-26 16:00:00  -5.492  4.287 -9.132  2.274  3.533  1.675
17417   17417 2018-06-26 17:00:00   2.813  3.818 -0.817  2.097  3.716  1.523
17418   17418 2018-06-26 18:00:00   9.243  3.818  5.472  2.097  3.655  1.432
17419   17419 2018-06-26 19:00:00  10.114  3.550  6.183  1.564  3.716  1.462

              OT
0      30.531000
1      27.787001
2      27.787001
3      25.044001
4      21.948000
...          ...
17415  10.904000
17416  11.044000
17417  10.271000
17418   9.778000
17419   9.567000

[17420 rows x 9 columns]>

In [27]:
DF=df.resample("D", on="date").mean()

In [28]:
# hourly average value for each day
DF.head(10)

,TimeID,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
date,,,,,,,,
2016-07-01,11.5,5.322042,2.603625,1.986958,0.898750,3.312333,1.496208,21.071833
2016-07-02,35.5,8.009500,4.108208,5.127417,2.009125,2.868292,1.639750,22.039208
2016-07-03,59.5,10.496333,4.995625,7.176625,2.542208,3.326417,1.879458,26.626375
2016-07-04,83.5,10.501875,5.408583,6.956125,2.728833,3.353000,1.906208,27.162666
2016-07-05,107.5,11.369917,5.377833,7.711125,2.682833,3.545917,2.014042,30.102583
2016-07-06,131.5,10.800500,4.738875,7.414917,2.292083,3.224833,1.813625,30.020667
2016-07-07,155.5,11.802375,4.853208,8.617292,2.465292,3.101708,1.672625,31.204791
2016-07-08,179.5,11.481458,4.591000,7.934750,2.246083,3.426750,1.719667,31.269250
2016-07-09,203.5,11.849958,4.532292,8.291542,2.130583,3.394917,1.714542,30.366500
2016-07-10,227.5,11.196750,4.015958,7.293500,1.727875,3.783250,1.665208,29.331709

In [29]:
DF.to_csv("oil station 1 hourly average for each day.csv")

In [31]:
#df = pd.read_fwf('GSE6186_series_matrix.txt')
df2 = pd.read_csv('oil temperature 2.csv', parse_dates=["date"])
DF2=df2.resample("D", on="date").mean()
DF2.to_csv("oil station 2 hourly average for each day.csv")

In [9]:
df.columns

Index(['TimeID', 'date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT'], dtype='object')

In [10]:
df1 = df[['date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT']]

In [11]:
df1.head(10)

            date   HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
0  7/1/2016 0:00  5.827  2.009  1.599  0.462  4.203  1.340  30.531000
1  7/1/2016 1:00  5.693  2.076  1.492  0.426  4.142  1.371  27.787001
2  7/1/2016 2:00  5.157  1.741  1.279  0.355  3.777  1.218  27.787001
3  7/1/2016 3:00  5.090  1.942  1.279  0.391  3.807  1.279  25.044001
4  7/1/2016 4:00  5.358  1.942  1.492  0.462  3.868  1.279  21.948000
5  7/1/2016 5:00  5.626  2.143  1.528  0.533  4.051  1.371  21.174000
6  7/1/2016 6:00  7.167  2.947  2.132  0.782  5.026  1.858  22.792000
7  7/1/2016 7:00  7.435  3.282  2.310  1.031  5.087  2.224  23.143999
8  7/1/2016 8:00  5.559  3.014  2.452  1.173  2.955  1.432  21.667000
9  7/1/2016 9:00  4.555  2.545  1.919  0.817  2.680  1.371  17.445999

In [13]:
df1.

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

In [ ]:
# every 24 hours, get an average

In [7]:
df.resample('6H', on = 'date').sum()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'